version: '2.0'

networks:
  my-network:
    external: true  # Ensuring the network is defined externally

services:
  ohio_service:
    container_name: ohio_service
    build: .  # Build from the current directory
    networks:
      - my-network  # Connect to the external network
    ports:
      - "8080:5000"  # Exposing container port 5000 to host port 8080
    volumes:
      - ./data:/apps/database.db  # Ensure the database file can persist across restarts

